"""empty message

Revision ID: 788cdc484116
Revises: 07f77c78fbeb
Create Date: 2022-12-15 02:06:34.930061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788cdc484116'
down_revision = '07f77c78fbeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
