"""empty message

Revision ID: d1e38b51800e
Revises: 788cdc484116
Create Date: 2022-12-17 00:01:19.095149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e38b51800e'
down_revision = '788cdc484116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('date_added', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_characters', sa.Integer(), nullable=True),
    sa.Column('favorite_planets', sa.Integer(), nullable=True),
    sa.Column('favorite_vehicles', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date_added'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('vehicles',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('crew', sa.Integer(), nullable=True),
    sa.Column('vehicle_class', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('vehicle_id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_from', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birth_year', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['planet_from'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('climate', sa.String(length=120), nullable=True))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('climate')
        batch_op.drop_column('population')
        batch_op.drop_column('diameter')
        batch_op.drop_column('planet_id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('birth_year')
        batch_op.drop_column('planet_from')

    op.drop_table('vehicles')
    op.drop_table('favorites')
    # ### end Alembic commands ###
